import type { Metadata } from 'next'
import { Archivo } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'

const archivo = Archivo({
  variable: '--font-archivo',
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>): ReactNode {
  return (
    <html lang="en">
      <body className={`${archivo.variable} antialiased font-archivo`}>
        {children}
      </body>
    </html>
  )
}
